package POO_Proy_Paquete;

import java.awt.Color;

public class app2 extends javax.swing.JFrame {
    public app2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        rojo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        tgs = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        caf = new javax.swing.JLabel();
        badatos = new javax.swing.JLabel();
        ciu = new javax.swing.JLabel();
        esinf = new javax.swing.JLabel();
        mat = new javax.swing.JLabel();
        poo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rojo.setBackground(new java.awt.Color(255, 51, 51));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("NOMBRE Y APELLIDO");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("PERFIL");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POO_Proy_Paquete_img/usuario-de-perfil (2).png"))); // NOI18N

        javax.swing.GroupLayout rojoLayout = new javax.swing.GroupLayout(rojo);
        rojo.setLayout(rojoLayout);
        rojoLayout.setHorizontalGroup(
            rojoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rojoLayout.createSequentialGroup()
                .addGroup(rojoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rojoLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel3)
                        .addGap(0, 8, Short.MAX_VALUE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rojoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );
        rojoLayout.setVerticalGroup(
            rojoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rojoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(168, Short.MAX_VALUE))
        );

        bg.add(rojo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 470));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        bg.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, 540, 20));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("CURSOS ASIGNADOS");
        bg.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 160, 30));

        tgs.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tgs.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tgs.setText("TEORÍA GENERAL DE SISTEMAS");
        tgs.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bg.add(tgs, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 360, 220, 30));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        bg.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 450, 540, 20));

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        bg.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, 540, 20));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("CICLO II - AGOSTO 2024");
        bg.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, 160, 30));

        caf.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        caf.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        caf.setText("CÁLCULO APLICADO A LA FÍSICA");
        caf.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bg.add(caf, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 230, 30));

        badatos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        badatos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        badatos.setText("BASE DE DATOS");
        badatos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bg.add(badatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, 160, 30));

        ciu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ciu.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ciu.setText("CIUDADANÍA Y ÉTICA");
        ciu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bg.add(ciu, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 160, 30));

        esinf.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        esinf.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        esinf.setText("ESTADÍSTICA INFERENCIAL");
        esinf.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bg.add(esinf, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, 190, 30));

        mat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        mat.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        mat.setText("MATEMÁTICA PARA INGENIEROS");
        mat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                matMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                matMouseExited(evt);
            }
        });
        bg.add(mat, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, 230, 30));

        poo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        poo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        poo.setText("PROGRAMACIÓN ORIENTADA A OBJETOS");
        poo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bg.add(poo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, 290, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void matMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_matMouseEntered
        mat.setBackground(Color.gray);
    }//GEN-LAST:event_matMouseEntered

    private void matMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_matMouseExited
        mat.setBackground(Color.white);
    }//GEN-LAST:event_matMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(app2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(app2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(app2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(app2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new app2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel badatos;
    private javax.swing.JPanel bg;
    private javax.swing.JLabel caf;
    private javax.swing.JLabel ciu;
    private javax.swing.JLabel esinf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel mat;
    private javax.swing.JLabel poo;
    private javax.swing.JPanel rojo;
    private javax.swing.JLabel tgs;
    // End of variables declaration//GEN-END:variables
}
